[project]
name = "asteroids"
version = "0.1.0"
description = "An Asteroids game built with Python and Pygame."
authors = [
    { name = "Dalton Dayton", email = "50755420+DaltonDayton@users.noreply.github.com" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame>=2.6.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]

[project.scripts]
asteroids = "asteroids.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = true

